In [1]:
import numpy as np 

In [3]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [9]:
c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [11]:
c[0] = 100
c

array([100,   1,   2,   3,   4])

In [13]:
d = c[1:4] 
d

array([1, 2, 3])

In [15]:
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [17]:
select = [0, 2, 3]

In [19]:
d = c[select]
d

array([100,   2, 300])

In [21]:
c[select] = 100000
c

array([100000,      1, 100000, 100000,    400])

In [23]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [25]:
a.size

5

In [27]:
a.shape

(5,)

In [29]:
a.ndim

1

In [31]:
b = np.ones((3,5))   
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
d = np.eye(3)        
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
a= np.zeros((4,4))  
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
x = [[1,2,3],
     [4,5,6], 
     [4,9,0]]

print(x)

[[1, 2, 3], [4, 5, 6], [4, 9, 0]]


In [39]:
a = np.array([[1,2,3],[4,5,6], [4,9,0]], dtype='float64') 
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [4. 9. 0.]]


In [41]:
a[1, 2]

6.0

In [43]:
x[1][2]

6

In [45]:
print(type(a))

<class 'numpy.ndarray'>


In [47]:
a[0]

array([1., 2., 3.])

In [49]:
a[0][2]

3.0

In [51]:
a[1:3]

array([[4., 5., 6.],
       [4., 9., 0.]])

In [53]:
a[1:3, 1:3]

array([[5., 6.],
       [9., 0.]])

In [55]:
a.ndim

2

In [57]:
a.size

9

In [59]:
a.dtype

dtype('float64')

In [62]:
a.itemsize

8

In [64]:
a.shape

(3, 3)

In [66]:
a = np.array([[3,5,2,7], [9,0,1,6]])
a

array([[3, 5, 2, 7],
       [9, 0, 1, 6]])

In [68]:
a_1 = np.reshape(a, (4, 2))
a_1

array([[3, 5],
       [2, 7],
       [9, 0],
       [1, 6]])

In [70]:
a=a.flatten()
a

array([3, 5, 2, 7, 9, 0, 1, 6])

In [72]:
a.shape

(8,)

In [74]:
a = np.array([1, -1, 3, 2, 1, -1])

In [76]:
mean = a.mean()
mean

0.8333333333333334

In [78]:
standard_deviation=a.std()
standard_deviation

1.4624940645653537

In [80]:
max_a = a.max()
max_a

3

In [82]:
min_a = a.min()
min_a

-1

In [84]:
amax = np.argmax(a)
amax

2

In [86]:
amin = np.argmin(a)
amin

1

In [88]:
u = np.array([1, 120])
v = np.array([10, 1])
z = u + v
z

array([ 11, 121])

In [90]:
Y = np.array([[2, 1], [1, 2]]) 
Z = np.array([[2, 1], [1, 2]]) 
X = Y * Z
X

array([[4, 1],
       [1, 4]])

In [92]:
y = np.array([1, 2])
z = 2 * y
z

array([2, 4])

In [94]:
u = np.array([1, 2])
v = np.array([3, 2])
z = u * v
z

array([3, 4])

In [96]:
np.dot(u, v)

7

In [98]:
A = np.array([[0, 1], [1, 0]])
B = np.array([[1, 2], [0, 2]])
C = np.dot(A,B)
C


array([[0, 2],
       [1, 2]])

In [100]:
C.T # Transopose of a matrix

array([[0, 1],
       [2, 2]])

In [102]:
u = np.array([1, 2, 3, -1]) 
print(u)
u[2] =  u[2] +1
u

[ 1  2  3 -1]


array([ 1,  2,  4, -1])

In [104]:
np.pi

3.141592653589793

In [106]:
x = np.array([0, np.pi/2 , np.pi])
x

array([0.        , 1.57079633, 3.14159265])

In [108]:
y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [110]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [112]:
print(a[a > 2]) # return values of 'a'  greater than 2

[3 4 5 6]


In [114]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [116]:
np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [118]:
np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [122]:
x = np.linspace(0, 2*np.pi, num=100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [124]:
y = np.sin(x)
y

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -